//! Recovery of stored ghostkeys from previous delegate versions.
//!
//! Every change to the delegate WASM re-keys the delegate -- its key is
//! `BLAKE3(BLAKE3(wasm) || params)` -- which moves the secret namespace it
//! reads and writes. Secrets stored under a predecessor are not deleted, only
//! unreachable, so the vault walks `legacy_delegates.toml` on startup and
//! re-imports whatever it finds.
//!
//! On a hosted node this is the *only* safety net. freenet-core's own
//! predecessor copy-forward deliberately skips user-scope secrets (the
//! per-user DEK is not derivable at rest), so nothing else will carry a
//! hosted user's keys across a re-key.

/// How many inconclusive passes to make before accepting that a definite
/// answer is not coming, and letting the migration rest.
///
/// A ceiling is required because "undetermined" is also what an unhealthy or
/// offline node looks like. Without one, a node that never answers would make
/// the vault re-probe every legacy delegate on every open, forever.
const MAX_MIGRATION_ATTEMPTS: u32 = 5;

/// What one pass over the legacy delegate table established.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
pub(crate) struct MigrationOutcome {
    /// Keys successfully re-imported under the current delegate.
    pub migrated: usize,
    /// Legacy delegates that gave no definite answer. We do not know whether
    /// these hold keys, so the migration cannot be called finished.
    pub undetermined: usize,
    /// Keys a legacy delegate handed over that would not re-import. These are
    /// still only in the predecessor.
    pub failed_imports: usize,
}

impl MigrationOutcome {
    /// True only when every legacy delegate answered *and* every key it held
    /// was re-imported -- the sole state in which "there is nothing left to
    /// migrate" is a fact rather than an assumption.
    pub(crate) fn is_conclusive(&self) -> bool {
        self.undetermined == 0 && self.failed_imports == 0
    }
}

/// Whether to record the migration as finished.
///
/// Recording it is what stops the vault ever looking again, so an
/// inconclusive pass must not record it. The previous implementation recorded
/// it unconditionally at the end of every run, so one transient failure -- a
/// node still starting up, a five-second timeout -- permanently stranded the
/// user's keys under a predecessor delegate, with nothing but a console line
/// to say so. That is the shape of the loss reported in freenet/ghostkeys#3.
pub(crate) fn should_mark_done(outcome: &MigrationOutcome, attempts_so_far: u32) -> bool {
    outcome.is_conclusive() || attempts_so_far + 1 >= MAX_MIGRATION_ATTEMPTS
}

/// Recover ghostkeys stored under earlier delegate versions.
pub async fn try_migrate() {
    #[cfg(all(
        target_family = "wasm",
        not(any(feature = "no-sync", feature = "example-data"))
    ))]
    real::run().await;
}

#[cfg(all(
    target_family = "wasm",
    not(any(feature = "no-sync", feature = "example-data"))
))]
mod real {
    use dioxus::logger::tracing::{info, warn};
    use freenet_stdlib::prelude::{CodeHash, DelegateKey};
    use ghostkey_common::{GhostKeyInfo, GhostkeyRequest, GhostkeyResponse};

    use super::{should_mark_done, MigrationOutcome};
    use crate::api;
    use crate::api::delegate::DelegateCallError;
    use crate::components::ghostkey_list;
    use crate::components::toast::{self, ToastKind};

    // Generated by build.rs from legacy_delegates.toml
    include!(concat!(env!("OUT_DIR"), "/legacy_delegates.rs"));

    const MIGRATION_FLAG: &str = "ghostkey_migration_done";
    const MIGRATION_ATTEMPTS: &str = "ghostkey_migration_attempts";

    /// Seconds to wait for a legacy delegate to answer. A registered delegate
    /// runs locally and replies fast, and an unregistered one now fails
    /// immediately via `DelegateCallError::NotRegistered`, so this deadline is
    /// only reached when the node itself is unresponsive.
    const LEGACY_PROBE_TIMEOUT_SECS: u64 = 5;

    pub(super) async fn run() {
        if LEGACY_DELEGATES.is_empty() || is_migration_done() {
            return;
        }

        let attempts = read_attempts();
        info!(
            "Checking {} legacy delegate(s) for stored ghostkeys (attempt {})",
            LEGACY_DELEGATES.len(),
            attempts + 1
        );

        let outcome = run_pass().await;
        report(&outcome);

        if should_mark_done(&outcome, attempts) {
            mark_migration_done();
        } else {
            write_attempts(attempts + 1);
        }
    }

    /// One sweep of the legacy delegate table.
    ///
    /// Probes are sequential on purpose: `send_to_delegate` holds the
    /// `WEB_API` write guard across its await, so two concurrent delegate
    /// calls would double-borrow and panic.
    async fn run_pass() -> MigrationOutcome {
        let current_key = api::delegate::get_current_delegate_key();
        let mut outcome = MigrationOutcome::default();

        for (delegate_key_bytes, code_hash_bytes) in LEGACY_DELEGATES {
            let legacy_key = DelegateKey::new(*delegate_key_bytes, CodeHash::new(*code_hash_bytes));
            if legacy_key == current_key {
                continue;
            }

            let exported = match api::delegate::send_to_delegate(
                &legacy_key,
                GhostkeyRequest::ExportAllGhostKeys,
                LEGACY_PROBE_TIMEOUT_SECS,
            )
            .await
            {
                Ok(GhostkeyResponse::ExportAllResult { keys }) => keys,
                // The node has no such delegate registered, so it cannot be
                // holding secrets: this entry is settled, not unknown. It is
                // also the common case, since most nodes never ran most
                // previous vault versions.
                Err(DelegateCallError::NotRegistered) => continue,
                Err(e) => {
                    warn!("Legacy delegate {} undetermined: {e}", legacy_key.encode());
                    outcome.undetermined += 1;
                    continue;
                }
                Ok(other) => {
                    warn!("Unexpected reply from legacy delegate: {other:?}");
                    outcome.undetermined += 1;
                    continue;
                }
            };

            if exported.is_empty() {
                continue;
            }
            info!(
                "Found {} ghostkey(s) under legacy delegate {}",
                exported.len(),
                legacy_key.encode()
            );

            for key in &exported {
                match api::delegate::send_request(GhostkeyRequest::ImportGhostKey {
                    certificate_pem: key.certificate_pem.clone(),
                    signing_key_pem: key.signing_key_pem.clone(),
                    master_verifying_key_pem: None,
                })
                .await
                {
                    Ok(GhostkeyResponse::ImportResult {
                        fingerprint,
                        notary_info,
                    }) => {
                        info!("Recovered ghostkey {fingerprint}");
                        ghostkey_list::add_ghostkey(GhostKeyInfo {
                            fingerprint: fingerprint.clone(),
                            label: key.label.clone(),
                            notary_info,
                            verifying_key_bytes: None,
                        });
                        outcome.migrated += 1;

                        if let Some(label) = &key.label {
                            let _ = api::delegate::send_request(GhostkeyRequest::SetLabel {
                                fingerprint,
                                label: label.clone(),
                            })
                            .await;
                        }
                    }
                    // Anything else means the key is still only in the
                    // predecessor. Counting it as migrated would let the pass
                    // report success and seal the flag over a key we failed to
                    // move.
                    other => {
                        warn!("Could not re-import {}: {other:?}", key.fingerprint);
                        outcome.failed_imports += 1;
                    }
                }
            }
        }

        outcome
    }

    fn report(outcome: &MigrationOutcome) {
        if outcome.migrated > 0 {
            toast::show(
                format!(
                    "Recovered {} ghostkey(s) from a previous vault version",
                    outcome.migrated
                ),
                ToastKind::Success,
            );
        }

        if !outcome.is_conclusive() {
            warn!(
                "Migration inconclusive: {} undetermined delegate(s), {} failed import(s)",
                outcome.undetermined, outcome.failed_imports
            );
            toast::show(
                "Could not check every previous vault version for stored ghostkeys. \
                 If an identity is missing, reopen the vault once your node is fully \
                 started, or re-import it from your backup.",
                ToastKind::Error,
            );
        }
    }

    fn local_storage() -> Option<web_sys::Storage> {
        web_sys::window().and_then(|w| w.local_storage().ok().flatten())
    }

    fn current_delegate_id() -> String {
        api::delegate::get_current_delegate_key().encode()
    }

    /// Both markers are namespaced by the current delegate id so a republish
    /// starts the recovery over: the new delegate has a fresh namespace, and
    /// its predecessor is exactly what we then need to sweep.
    fn is_migration_done() -> bool {
        local_storage()
            .and_then(|s| s.get_item(MIGRATION_FLAG).ok().flatten())
            .is_some_and(|stored| stored == current_delegate_id())
    }

    fn mark_migration_done() {
        if let Some(storage) = local_storage() {
            let _ = storage.set_item(MIGRATION_FLAG, &current_delegate_id());
        }
    }

    fn read_attempts() -> u32 {
        let current = current_delegate_id();
        local_storage()
            .and_then(|s| s.get_item(MIGRATION_ATTEMPTS).ok().flatten())
            .and_then(|stored| {
                let (id, count) = stored.split_once(':')?;
                if id == current {
                    count.parse().ok()
                } else {
                    None
                }
            })
            .unwrap_or(0)
    }

    fn write_attempts(attempts: u32) {
        if let Some(storage) = local_storage() {
            let _ = storage.set_item(
                MIGRATION_ATTEMPTS,
                &format!("{}:{attempts}", current_delegate_id()),
            );
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn outcome(migrated: usize, undetermined: usize, failed_imports: usize) -> MigrationOutcome {
        MigrationOutcome {
            migrated,
            undetermined,
            failed_imports,
        }
    }

    #[test]
    fn a_pass_that_found_nothing_is_conclusive() {
        assert!(outcome(0, 0, 0).is_conclusive());
        assert!(should_mark_done(&outcome(0, 0, 0), 0));
    }

    #[test]
    fn a_pass_that_recovered_everything_is_conclusive() {
        assert!(outcome(3, 0, 0).is_conclusive());
        assert!(should_mark_done(&outcome(3, 0, 0), 0));
    }

    /// Regression for the loss behind freenet/ghostkeys#3: the old
    /// implementation recorded the migration as finished no matter what
    /// happened, so one unreachable legacy delegate sealed the flag and left
    /// the user's keys stranded under a predecessor.
    #[test]
    fn an_undetermined_delegate_leaves_the_migration_open() {
        let o = outcome(0, 1, 0);
        assert!(!o.is_conclusive());
        assert!(!should_mark_done(&o, 0));
    }

    /// A key pulled out of a predecessor but not re-imported is still only in
    /// the predecessor, so the pass has not finished its job.
    #[test]
    fn a_failed_import_leaves_the_migration_open() {
        let o = outcome(1, 0, 1);
        assert!(!o.is_conclusive());
        assert!(!should_mark_done(&o, 0));
    }

    #[test]
    fn an_inconclusive_pass_gives_up_at_the_attempt_ceiling() {
        let o = outcome(0, 1, 0);
        for attempts in 0..MAX_MIGRATION_ATTEMPTS - 1 {
            assert!(
                !should_mark_done(&o, attempts),
                "gave up after {attempts} attempt(s), before the ceiling"
            );
        }
        assert!(should_mark_done(&o, MAX_MIGRATION_ATTEMPTS - 1));
    }
}
