//! Recovery of stored ghostkeys from previous delegate versions.
//!
//! Every change to the delegate WASM re-keys the delegate -- its key is
//! `BLAKE3(BLAKE3(wasm) || params)` -- which moves the secret namespace it
//! reads and writes. Secrets stored under a predecessor are not deleted, only
//! unreachable, so the vault sweeps `legacy_delegates.toml` on startup and
//! re-imports whatever it finds.
//!
//! On a hosted node this is the *only* safety net. freenet-core's own
//! predecessor copy-forward deliberately skips user-scope secrets (the
//! per-user DEK is not derivable at rest), so nothing else will carry a
//! hosted user's keys across a re-key.
//!
//! # Why there is no "migration done" flag
//!
//! There used to be one, in `localStorage`, and it never did anything: the
//! vault runs in the shell's iframe, which is sandboxed without
//! `allow-same-origin`, so its origin is opaque and every `localStorage`
//! access throws. Verified against a live node -- the app frame reports
//! `SecurityError: The document is sandboxed and lacks the 'allow-same-origin'
//! flag`, while the top-level shell reads and writes storage normally.
//!
//! It should not come back even if storage becomes available, because no
//! available signal would justify setting it. The obvious candidate -- "the
//! node says that delegate is not registered" -- is not proof of absence (see
//! `DelegateCallError::NotRegistered`), and neither is an empty export:
//! `ExportAllGhostKeys` silently skips any key the caller lacks `Export` scope
//! on, or whose material fails to decode, and the reply carries no count to
//! check against. A flag that permanently stops the vault looking, set on
//! evidence that cannot support it, is exactly how keys get stranded.
//!
//! Sweeping on every startup is therefore the behaviour, not a fallback --
//! and measured against a live node, it is also what already happens today,
//! since the flag never persisted.
//!
//! It is not free. A node that does not have a given legacy delegate does not
//! answer the probe *at all* -- verified by driving the published vault in a
//! browser: nine legacy entries, nine `Timeout waiting for delegate response`,
//! and no error response for any of them. So the sweep costs one full deadline
//! per absent entry. Two things keep that tolerable: it runs after the vault
//! has already loaded and rendered what the current delegate holds, so the
//! user is never waiting on it, and the deadline is sized for a local WASM
//! call rather than a network round trip.

/// What one pass over the legacy delegate table established. Reported to the
/// user; it does not gate anything.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
pub(crate) struct MigrationOutcome {
    /// Keys recovered that the current delegate did not already hold.
    pub recovered: usize,
    /// Legacy delegates that gave no definite answer, so we do not know
    /// whether they hold keys.
    pub undetermined: usize,
    /// Keys a legacy delegate handed over that would not re-import.
    pub failed_imports: usize,
}

impl MigrationOutcome {
    /// Whether every legacy delegate answered and every key it offered was
    /// re-imported. Purely a reporting distinction -- the sweep runs again on
    /// the next startup either way.
    pub(crate) fn is_conclusive(&self) -> bool {
        self.undetermined == 0 && self.failed_imports == 0
    }

    /// Whether the user needs telling that something could not be checked.
    pub(crate) fn needs_user_attention(&self) -> bool {
        !self.is_conclusive()
    }
}

/// Recover ghostkeys stored under earlier delegate versions.
///
/// `already_held` is the set of fingerprints the current delegate already has,
/// so a key present in both is neither re-imported nor reported as recovered
/// on every startup.
pub async fn try_migrate(already_held: Vec<String>) {
    #[cfg(all(
        target_family = "wasm",
        not(any(feature = "no-sync", feature = "example-data"))
    ))]
    real::run(already_held).await;

    #[cfg(not(all(
        target_family = "wasm",
        not(any(feature = "no-sync", feature = "example-data"))
    )))]
    let _ = already_held;
}

#[cfg(all(
    target_family = "wasm",
    not(any(feature = "no-sync", feature = "example-data"))
))]
mod real {
    use std::collections::BTreeSet;

    use dioxus::logger::tracing::{info, warn};
    use freenet_stdlib::prelude::{CodeHash, DelegateKey};
    use ghostkey_common::{GhostKeyInfo, GhostkeyRequest, GhostkeyResponse};

    use super::MigrationOutcome;
    use crate::api;
    use crate::api::delegate::DelegateCallError;
    use crate::components::ghostkey_list;
    use crate::components::toast::{self, ToastKind};

    // Generated by build.rs from legacy_delegates.toml
    include!(concat!(env!("OUT_DIR"), "/legacy_delegates.rs"));

    /// Seconds to wait for a legacy delegate to answer.
    ///
    /// A delegate the node actually has is a local WASM call that answers in
    /// milliseconds, so this only ever bounds the wait for one the node does
    /// not have -- and those never answer, so the deadline is paid in full for
    /// each. At the previous 5s, ten entries meant ~50s of background probing
    /// on every vault open. Erring short is safe: a legacy delegate that does
    /// not answer in time is recorded as undetermined and the user is told,
    /// rather than being silently written off.
    const LEGACY_PROBE_TIMEOUT_SECS: u64 = 3;

    pub(super) async fn run(already_held: Vec<String>) {
        if LEGACY_DELEGATES.is_empty() {
            return;
        }

        info!(
            "Sweeping {} legacy delegate(s) for stored ghostkeys",
            LEGACY_DELEGATES.len()
        );

        let outcome = run_pass(already_held.into_iter().collect()).await;
        report(&outcome);
    }

    /// One sweep of the legacy delegate table.
    async fn run_pass(mut held: BTreeSet<String>) -> MigrationOutcome {
        let current_key = api::delegate::get_current_delegate_key();
        let mut outcome = MigrationOutcome::default();

        for (delegate_key_bytes, code_hash_bytes) in LEGACY_DELEGATES {
            let legacy_key = DelegateKey::new(*delegate_key_bytes, CodeHash::new(*code_hash_bytes));
            if legacy_key == current_key {
                continue;
            }

            let exported = match api::delegate::send_to_delegate(
                &legacy_key,
                GhostkeyRequest::ExportAllGhostKeys,
                LEGACY_PROBE_TIMEOUT_SECS,
            )
            .await
            {
                Ok(GhostkeyResponse::ExportAllResult { keys }) => keys,
                // Skip cheaply, but do NOT read this as "nothing is stored
                // here": the node synthesizes it from a backoff throttle, and
                // an unregistered delegate can still own secrets. Nothing is
                // sealed on the strength of it -- the next startup asks again.
                Err(DelegateCallError::NotRegistered) => continue,
                Err(e) => {
                    warn!("Legacy delegate {} undetermined: {e}", legacy_key.encode());
                    outcome.undetermined += 1;
                    continue;
                }
                Ok(other) => {
                    warn!("Unexpected reply from legacy delegate: {other:?}");
                    outcome.undetermined += 1;
                    continue;
                }
            };

            for key in &exported {
                // Already in the current delegate: skip, so a predecessor that
                // keeps its copy forever does not re-import and re-announce
                // the same identities on every startup.
                if held.contains(&key.fingerprint) {
                    continue;
                }

                match api::delegate::send_request(GhostkeyRequest::ImportGhostKey {
                    certificate_pem: key.certificate_pem.clone(),
                    signing_key_pem: key.signing_key_pem.clone(),
                    master_verifying_key_pem: None,
                })
                .await
                {
                    Ok(GhostkeyResponse::ImportResult {
                        fingerprint,
                        notary_info,
                    }) => {
                        info!("Recovered ghostkey {fingerprint}");
                        held.insert(fingerprint.clone());
                        ghostkey_list::add_ghostkey(GhostKeyInfo {
                            fingerprint: fingerprint.clone(),
                            label: key.label.clone(),
                            notary_info,
                            verifying_key_bytes: None,
                        });
                        outcome.recovered += 1;

                        if let Some(label) = &key.label {
                            let _ = api::delegate::send_request(GhostkeyRequest::SetLabel {
                                fingerprint,
                                label: label.clone(),
                            })
                            .await;
                        }
                    }
                    // The key is still only in the predecessor. Counting it as
                    // recovered would report a success that did not happen.
                    other => {
                        warn!("Could not re-import {}: {other:?}", key.fingerprint);
                        outcome.failed_imports += 1;
                    }
                }
            }
        }

        outcome
    }

    fn report(outcome: &MigrationOutcome) {
        if outcome.recovered > 0 {
            toast::show(
                format!(
                    "Recovered {} ghostkey(s) from a previous vault version",
                    outcome.recovered
                ),
                ToastKind::Success,
            );
        }

        if outcome.needs_user_attention() {
            warn!(
                "Migration sweep incomplete: {} undetermined delegate(s), {} failed import(s)",
                outcome.undetermined, outcome.failed_imports
            );
            toast::show(
                "Could not check every previous vault version for stored ghostkeys. \
                 If an identity is missing, reopen the vault once your node is fully \
                 started, or re-import it from your backup.",
                ToastKind::Error,
            );
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn outcome(recovered: usize, undetermined: usize, failed_imports: usize) -> MigrationOutcome {
        MigrationOutcome {
            recovered,
            undetermined,
            failed_imports,
        }
    }

    #[test]
    fn a_pass_that_found_nothing_is_conclusive() {
        assert!(outcome(0, 0, 0).is_conclusive());
        assert!(!outcome(0, 0, 0).needs_user_attention());
    }

    #[test]
    fn a_pass_that_recovered_everything_is_conclusive() {
        assert!(outcome(3, 0, 0).is_conclusive());
        assert!(!outcome(3, 0, 0).needs_user_attention());
    }

    /// A legacy delegate we could not reach may still be holding keys, so the
    /// user has to be told rather than left with a silently partial sweep.
    #[test]
    fn an_undetermined_delegate_needs_user_attention() {
        let o = outcome(0, 1, 0);
        assert!(!o.is_conclusive());
        assert!(o.needs_user_attention());
    }

    /// A key pulled out of a predecessor but not re-imported is still only in
    /// the predecessor, even though the sweep otherwise completed.
    #[test]
    fn a_failed_import_needs_user_attention() {
        let o = outcome(1, 0, 1);
        assert!(!o.is_conclusive());
        assert!(o.needs_user_attention());
    }

    /// Recovering keys does not excuse an entry we could not check.
    #[test]
    fn recovery_does_not_mask_an_unchecked_delegate() {
        let o = outcome(5, 1, 0);
        assert!(o.needs_user_attention());
    }
}
