use dioxus::logger::tracing::info;

// Generated by build.rs from legacy_delegates.toml
include!(concat!(env!("OUT_DIR"), "/legacy_delegates.rs"));

/// Log legacy delegate info on startup for debugging.
/// Full automated migration requires the old delegate WASM to still be
/// registered on the node -- for now we record the keys and warn.
pub fn log_legacy_info() {
    if LEGACY_DELEGATES.is_empty() {
        return;
    }
    info!(
        "{} legacy delegate key(s) recorded for future migration",
        LEGACY_DELEGATES.len()
    );
}
