[application]
name = "ghostkey-ui"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "Ghostkey Manager"
base_path = "v1/contract/web/DLog47hEsrtuGT4N5XCeMBG45m4n1aWM89tBZXue2E1N"

[web.watcher]
reload_html = true
watch_path = ["src"]
